# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hermes_remote_pb2 as hermes__remote__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hermes_remote_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HermesAgentServiceStub:
    """HermesAgentService — протокол связи между Remote Agent и Orchestrator
    Агент подключается к Orchestrator и держит bidirectional stream
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/hermes_agent.HermesAgentService/Connect',
                request_serializer=hermes__remote__pb2.AgentMessage.SerializeToString,
                response_deserializer=hermes__remote__pb2.OrchestratorMessage.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/hermes_agent.HermesAgentService/HealthCheck',
                request_serializer=hermes__remote__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=hermes__remote__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GenerateAgentToken = channel.unary_unary(
                '/hermes_agent.HermesAgentService/GenerateAgentToken',
                request_serializer=hermes__remote__pb2.GenerateAgentTokenRequest.SerializeToString,
                response_deserializer=hermes__remote__pb2.GenerateAgentTokenResponse.FromString,
                _registered_method=True)
        self.RevokeAgentToken = channel.unary_unary(
                '/hermes_agent.HermesAgentService/RevokeAgentToken',
                request_serializer=hermes__remote__pb2.RevokeAgentTokenRequest.SerializeToString,
                response_deserializer=hermes__remote__pb2.RevokeAgentTokenResponse.FromString,
                _registered_method=True)
        self.ListAgentTokens = channel.unary_unary(
                '/hermes_agent.HermesAgentService/ListAgentTokens',
                request_serializer=hermes__remote__pb2.ListAgentTokensRequest.SerializeToString,
                response_deserializer=hermes__remote__pb2.ListAgentTokensResponse.FromString,
                _registered_method=True)


class HermesAgentServiceServicer:
    """HermesAgentService — протокол связи между Remote Agent и Orchestrator
    Агент подключается к Orchestrator и держит bidirectional stream
    """

    def Connect(self, request_iterator, context):
        """Connect — основной метод: агент подключается и обменивается сообщениями
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck — проверка связи (одноразовый вызов)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAgentToken(self, request, context):
        """GenerateAgentToken — генерация JWT токена для нового агента (admin only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAgentToken(self, request, context):
        """RevokeAgentToken — отзыв токена агента (admin only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentTokens(self, request, context):
        """ListAgentTokens — список всех токенов агентов (admin only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HermesAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=hermes__remote__pb2.AgentMessage.FromString,
                    response_serializer=hermes__remote__pb2.OrchestratorMessage.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=hermes__remote__pb2.HealthCheckRequest.FromString,
                    response_serializer=hermes__remote__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GenerateAgentToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAgentToken,
                    request_deserializer=hermes__remote__pb2.GenerateAgentTokenRequest.FromString,
                    response_serializer=hermes__remote__pb2.GenerateAgentTokenResponse.SerializeToString,
            ),
            'RevokeAgentToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAgentToken,
                    request_deserializer=hermes__remote__pb2.RevokeAgentTokenRequest.FromString,
                    response_serializer=hermes__remote__pb2.RevokeAgentTokenResponse.SerializeToString,
            ),
            'ListAgentTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentTokens,
                    request_deserializer=hermes__remote__pb2.ListAgentTokensRequest.FromString,
                    response_serializer=hermes__remote__pb2.ListAgentTokensResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hermes_agent.HermesAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hermes_agent.HermesAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HermesAgentService:
    """HermesAgentService — протокол связи между Remote Agent и Orchestrator
    Агент подключается к Orchestrator и держит bidirectional stream
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hermes_agent.HermesAgentService/Connect',
            hermes__remote__pb2.AgentMessage.SerializeToString,
            hermes__remote__pb2.OrchestratorMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes_agent.HermesAgentService/HealthCheck',
            hermes__remote__pb2.HealthCheckRequest.SerializeToString,
            hermes__remote__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAgentToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes_agent.HermesAgentService/GenerateAgentToken',
            hermes__remote__pb2.GenerateAgentTokenRequest.SerializeToString,
            hermes__remote__pb2.GenerateAgentTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAgentToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes_agent.HermesAgentService/RevokeAgentToken',
            hermes__remote__pb2.RevokeAgentTokenRequest.SerializeToString,
            hermes__remote__pb2.RevokeAgentTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgentTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes_agent.HermesAgentService/ListAgentTokens',
            hermes__remote__pb2.ListAgentTokensRequest.SerializeToString,
            hermes__remote__pb2.ListAgentTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
